# Generated by Django 4.2.5 on 2023-09-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('course', models.CharField(db_column='course', max_length=100)),
                ('date', models.DateTimeField(db_column='year', default=2000)),
            ],
        ),
    ]
