# Generated by Django 4.2.5 on 2023-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(default='teacher', max_length=100)),
                ('course', models.CharField(default='new course', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='studentname',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='myapp.course'),
        ),
    ]
